# Generated by Django 5.0.1 on 2024-01-24 11:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("brokennest", "0002_books_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="books",
            name="created_time",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
