# Generated by Django 5.0.1 on 2024-01-24 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("brokennest", "0003_books_created_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="books",
            name="created_time",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
